/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geststock.dialog;

import geststock.classes.Articlecommande;
import geststock.classes.ArticlecommandePK;
import geststock.classes.Articles;
import geststock.classes.Client;
import geststock.classes.Commande;
import geststock.classes.Facture;
import geststock.ecrans.CommandeEcran;
import geststock.utilities.OutilUtilities;
import java.io.File;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author ilboudo
 */
public class FactureDialog extends javax.swing.JDialog {

    private List<Articlecommande> articleCommandeList = new ArrayList<>();

    public List<Articlecommande> getArticleCommandeList() {
        return articleCommandeList;
    }

    public void setArticleCommandeList(List<Articlecommande> articleCommandeList) {
        this.articleCommandeList = articleCommandeList;
    }

    private JFrame precedent;
    /**
     * Creates new form FactureDialog
     */
    public FactureDialog(java.awt.Frame parent, boolean modal, List<Articlecommande> artscommande) {
        super(parent, modal);
        this.precedent=(JFrame) parent;
        initComponents();

        //Calculons les montant ht et ttc
        double ht = 0;
        double ttc = 0;
        this.articleCommandeList = artscommande;

        System.out.println(articleCommandeList.size() + "");
        for (Articlecommande ac : articleCommandeList) {
            ht = ht + ac.getPrixht();
            System.out.println(ht + ttc + "");
            ttc = ttc + ac.getPrixttc();
        }

        txt_totaux_ht.setText(ht + "");
        txt_totaux_ttc.setText(ttc + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_numero = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_totaux_ht = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_totaux_ttc = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_mtant_rendu = new javax.swing.JLabel();
        txt_rest_a_paye = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_tva = new javax.swing.JComboBox<>();
        spin_mtant_versee = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facture");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel1.setText("Nom:");

        jLabel2.setText("Prénom(s):");

        jLabel3.setText("Téléphone:");

        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txt_numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nom)
                    .addComponent(txt_prenom)
                    .addComponent(txt_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paiement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("TVA:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("TOTAUX  HT:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("TOTAUX  TTC:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("SOMME VERSEE:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("SOMME RENDUE:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("RESTE A PAYE:");

        txt_totaux_ht.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txt_totaux_ht.setForeground(new java.awt.Color(255, 0, 0));
        txt_totaux_ht.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("F CFA");

        txt_totaux_ttc.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txt_totaux_ttc.setForeground(new java.awt.Color(255, 0, 0));
        txt_totaux_ttc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("F CFA");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("F CFA");

        txt_mtant_rendu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txt_mtant_rendu.setForeground(new java.awt.Color(255, 0, 0));
        txt_mtant_rendu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_rest_a_paye.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txt_rest_a_paye.setForeground(new java.awt.Color(255, 0, 0));
        txt_rest_a_paye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("F CFA");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("F CFA");

        cb_tva.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cb_tva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUI", "NON" }));
        cb_tva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tvaItemStateChanged(evt);
            }
        });

        spin_mtant_versee.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        spin_mtant_versee.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_mtant_verseeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_totaux_ht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_totaux_ttc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mtant_rendu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_rest_a_paye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_tva, 0, 213, Short.MAX_VALUE)
                    .addComponent(spin_mtant_versee))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_totaux_ht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_totaux_ttc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spin_mtant_versee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_mtant_rendu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rest_a_paye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Okpx.png"))); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancelpx.png"))); // NOI18N
        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void spin_mtant_verseeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_mtant_verseeStateChanged
        // TODO add your handling code here:
        double mont_vers = Double.parseDouble(spin_mtant_versee.getValue().toString());
        double mnt_ht = Double.parseDouble(txt_totaux_ht.getText().toString());
        double mnt_ttc = Double.parseDouble(txt_totaux_ttc.getText().toString());
        if (cb_tva.getSelectedItem().toString().equals("OUI")) {
            //au cas ou on apploque la TVA
            if (mnt_ttc <= mont_vers) {
                txt_mtant_rendu.setText((mont_vers - mnt_ttc) + "");
                txt_rest_a_paye.setText("0");
            } else {
                txt_mtant_rendu.setText("0");
                txt_rest_a_paye.setText((-mont_vers + mnt_ttc) + "");
            }
        } else //au cas ou on n'apploque pas la TVA
         if (mnt_ht <= mont_vers) {
                txt_mtant_rendu.setText((mont_vers - mnt_ht) + "");
                txt_rest_a_paye.setText("0");
            } else {
                txt_mtant_rendu.setText("0");
                txt_rest_a_paye.setText((-mont_vers + mnt_ht) + "");
            }
    }//GEN-LAST:event_spin_mtant_verseeStateChanged

    private void cb_tvaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tvaItemStateChanged
        // TODO add your handling code here:

        double mont_vers = Double.parseDouble(spin_mtant_versee.getValue().toString());
        double mnt_ht = Double.parseDouble(txt_totaux_ht.getText().toString());
        double mnt_ttc = Double.parseDouble(txt_totaux_ttc.getText().toString());
        if (cb_tva.getSelectedItem().toString().equals("OUI")) {
            //au cas ou on apploque la TVA
            if (mnt_ttc <= mont_vers) {
                txt_mtant_rendu.setText((mont_vers - mnt_ttc) + "");
                txt_rest_a_paye.setText("0");
            } else {
                txt_mtant_rendu.setText("0");
                txt_rest_a_paye.setText((-mont_vers + mnt_ttc) + "");
            }
        } else //au cas ou on n'apploque pas la TVA
         if (mnt_ht <= mont_vers) {
                txt_mtant_rendu.setText((mont_vers - mnt_ht) + "");
                txt_rest_a_paye.setText("0");
            } else {
                txt_mtant_rendu.setText("0");
                txt_rest_a_paye.setText((-mont_vers + mnt_ht) + "");
            }

    }//GEN-LAST:event_cb_tvaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double mont_vers = Double.parseDouble(spin_mtant_versee.getValue().toString());
        double mnt_ht = Double.parseDouble(txt_totaux_ht.getText().toString());
        double mnt_ttc = Double.parseDouble(txt_totaux_ttc.getText().toString());
        double montant_rendu = 0;
        double reste_a_paye = 0;
        boolean tva = false;

        Commande commande = new Commande();
        Facture facture = new Facture();
        Client client = new Client();
        // ArticlecommandePK artcmandePK=new ArticlecommandePK();

        //articleCommandeList.get(0).setCommande(commande);
        if (cb_tva.getSelectedItem().toString().equals("OUI")) {
            tva = true;
            //au cas ou on apploque la TVA
            if (mnt_ttc <= mont_vers) {
                montant_rendu = mont_vers - mnt_ttc;
                reste_a_paye = 0;

//                txt_mtant_rendu.setText((mont_vers - mnt_ttc) + "");
//                txt_rest_a_paye.setText("0");
            } else {

                montant_rendu = 0;
                reste_a_paye = -mont_vers + mnt_ttc;
//                txt_mtant_rendu.setText("0");
//                txt_rest_a_paye.setText((-mont_vers + mnt_ttc) + "");
            }
        } else //au cas ou on n'apploque pas la TVA
        {
            tva = false;

            if (mnt_ht <= mont_vers) {

                montant_rendu = mont_vers - mnt_ht;
                reste_a_paye = 0;
//            txt_mtant_rendu.setText((mont_vers - mnt_ht) + "");
//            txt_rest_a_paye.setText("0");
            } else {

                montant_rendu = 0;
                reste_a_paye = -mont_vers + mnt_ht;
//            txt_mtant_rendu.setText("0");
//            txt_rest_a_paye.setText((-mont_vers + mnt_ht) + "");
            }
        }

        commande.setCreatedAt(new Date());
        commande.setCreatedBy(OutilUtilities.userActuel.getId());
        commande.setMontantHt(mnt_ht);
        commande.setMontantTtc(mnt_ttc);
        commande.setTva(tva);

        commande.setUpdatedAt(new Date());
        commande.setUpdatedBy(OutilUtilities.userActuel.getId());

        facture.setCreateAt(new Date());
        facture.setCreatedBy(OutilUtilities.userActuel.getId());
        facture.setUpdatedAt(new Date());
        facture.setUpdatedBy(OutilUtilities.userActuel.getId());
        facture.setModePayement("Espece");
        facture.setMontantHt(mnt_ht);
        facture.setMontantTtc(mnt_ttc);
        facture.setVersement(Integer.parseInt(spin_mtant_versee.getValue().toString()));
        facture.setRestePayer((int) reste_a_paye);//Integer.parseInt(txt_rest_a_paye.getText()));

        //Selon la valeur du reste a payer, nous pouvons deduire la valeur de la facyure
        if (reste_a_paye == 0) {
            commande.setValider(true);
            facture.setValeur_facture(mont_vers);
        } else {
            commande.setValider(false);
            facture.setValeur_facture(mont_vers);
        }

        client.setNom(txt_nom.getText().toString());
        client.setPrenom(txt_prenom.getText().toString());
        client.setTel(txt_numero.getText().toString());
        client.ajouterClient();
        commande.setIdclient(client);
        //commande.setArticlecommandeList(articleCommandeList);
        boolean b = commande.ajouterCommande();
        facture.setIdcommande(commande);

        facture.ajouerFacture();

        for (Articlecommande artc : articleCommandeList) {
            ArticlecommandePK artcommandePK = new ArticlecommandePK();

            artcommandePK.setIdarticle(artc.getArticles().getId());
            artc.setCommande(commande);
            artc.setCreatedAt(new Date());
            artc.setUpdatedAt(new Date());
            artc.setCreatedBy(OutilUtilities.userActuel.getId());
            artc.setUpdatedBy(OutilUtilities.userActuel.getId());
            artc.setArticlecommandePK(artcommandePK);

            Articles ar = artc.getArticles();

            artc.setPrix_vente(new Double(ar.getPrixVente()));

            artc.ajouterArticleCommande();

            ar.setQuantite(ar.getQuantite() - artc.getQuantite());
            ar.setUpdatedAt(new Date());
            ar.setUpdatedBy(OutilUtilities.userActuel.getId());

            ar.updateArticle();

        }

        System.out.println(b);
        File f = new File("src/Impressions/FactureTTC.jrxml");
        String sql = "select *,c.tva  as ctva,ac.prix_vente as pv from articlecommande ac,articles a,commande c,client cl where ac.idarticle=a.id and c.id=ac.idcommande and cl.idclient=c.idclient and c.id='" + commande.getId() + "'";

        HashMap<String, Object> parameters = new HashMap<>();
        parameters.put("param_id_facture", "00" + facture.getId());
        parameters.put("param_sum_versee", facture.getVersement() + " F CFA");
        parameters.put("param_reste_a_paye", facture.getRestePayer() + " F CFA");
        parameters.put("param_sum_remise", montant_rendu + " F CFA");
        //String ch="/home/ilboudo/Documents/GestStock/GESTSTOCK2/src/Impressions/FactureTTC.jrxml";
        OutilUtilities.afficherReport(f.getAbsolutePath(), sql, parameters);
        this.setVisible(false);
        this.dispose();
        this.precedent.setVisible(false);
        this.precedent.dispose();
        CommandeEcran com=new CommandeEcran();
        com.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactureDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                FactureDialog dialog = new FactureDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_tva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner spin_mtant_versee;
    private javax.swing.JLabel txt_mtant_rendu;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JFormattedTextField txt_numero;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JLabel txt_rest_a_paye;
    private javax.swing.JLabel txt_totaux_ht;
    private javax.swing.JLabel txt_totaux_ttc;
    // End of variables declaration//GEN-END:variables
}
